# Generated by Django 2.2.dev20190116210816 on 2019-01-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
