# Generated by Django 2.2.dev20190116210816 on 2019-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190116_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='price',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='state',
        ),
        migrations.AddField(
            model_name='carduser',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carduser',
            name='state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
