# Generated by Django 2.2.dev20190116210816 on 2019-01-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190116_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='selection',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
