# Generated by Django 2.2.dev20190116210816 on 2019-01-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_deck_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carduser',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='carduser',
            name='state',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='selection',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
