# Generated by Django 2.2.dev20190120170712 on 2019-01-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carduser',
            old_name='price',
            new_name='amount',
        ),
    ]
